{pkgs}: {
  deps = [
    pkgs.cairo
    pkgs.libxcrypt
    pkgs.pango
    pkgs.xorg.libXi
    pkgs.xorg.libXtst
    pkgs.xorg.libXrender
    pkgs.xorg.libXfixes
    pkgs.xorg.libXdamage
    pkgs.xorg.libXcomposite
    pkgs.xorg.libXrandr
    pkgs.libxkbcommon
    pkgs.chromium-xorg-conf
    pkgs.xorg.libxcb
    pkgs.jq
    pkgs.mesa
    pkgs.expat
    pkgs.libdrm
    pkgs.cups
    pkgs.at-spi2-atk
    pkgs.atk
    pkgs.nspr
    pkgs.nss
    pkgs.alsa-lib
    pkgs.dbus
    pkgs.gtk3
    pkgs.firefox
    pkgs.chromium
    pkgs.playwright-driver
    pkgs.gitFull
  ];
}
